version: '3'
services:
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "MyPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=testdb;User Id=sa;Password=MyPassword123!"
    depends_on:
      - db
