FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet build

FROM build AS test
WORKDIR /app/tests
COPY . .
RUN dotnet test --logger:trx

FROM build AS publish
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=publish /app/out .
EXPOSE 80
ENTRYPOINT ["dotnet", "my-web-app.dll"]